# -*- coding: utf-8 -*-
"""hackthon3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0kH4qk9sU7xXaibAZ8-mDa0fq1S054Q
"""



import random
import pandas as pd

# Set seed for reproducibility
random.seed(42)

NUM_RECORDS = 500

sports_list = ["Football", "Basketball", "Cricket", "Badminton", "Gymnastics", "Athletics"]

data = []

for _ in range(NUM_RECORDS):

    # ---------- Academic Life ----------
    attendance = round(random.uniform(60, 95), 2)
    gpa = round(random.uniform(5.5, 9.5), 2)
    study_hours = round(random.uniform(1.5, 6.5), 2)

    # ---------- Fitness & Gym ----------
    gym_visits = random.randint(0, 6)
    workout_duration = random.randint(30, 90)

    # ---------- Sports ----------
    preferred_sport = random.choice(sports_list)
    sports_hours = round(random.uniform(0, 8), 2)
    coach_guided = random.choice([0, 1])

    # ---------- Health & Balance ----------
    sleep_hours = round(random.uniform(5, 8), 2)

    # Stress increases with study hours and low sleep
    stress_level = int(
        min(
            10,
            max(
                1,
                (study_hours * 1.5) - (sleep_hours * 0.8) + random.uniform(1, 3)
            )
        )
    )

    # Time management improves with balanced study + fitness
    time_management = int(
        min(
            10,
            max(
                1,
                10 - abs(study_hours - 4) - (stress_level / 2) + random.uniform(0, 2)
            )
        )
    )

    # Fitness level depends on gym + sports
    fitness_level = int(
        min(
            10,
            max(
                1,
                (gym_visits * 1.2) + (sports_hours * 0.8) + random.uniform(1, 2)
            )
        )
    )

    # Sports skill improves with practice + coach guidance
    sports_skill = int(
        min(
            10,
            max(
                1,
                (sports_hours * 0.9) + (coach_guided * 2) + random.uniform(1, 2)
            )
        )
    )

    # ---------- Overall Personality Score ----------
    personality_score = int(
        min(
            10,
            max(
                1,
                (
                    (fitness_level * 0.25) +
                    (sports_skill * 0.25) +
                    (time_management * 0.2) +
                    (gpa * 0.2) -
                    (stress_level * 0.1)
                )
            )
        )
    )

    data.append([
        attendance,
        gpa,
        study_hours,
        gym_visits,
        workout_duration,
        preferred_sport,
        sports_hours,
        coach_guided,
        fitness_level,
        sports_skill,
        stress_level,
        sleep_hours,
        time_management,
        personality_score
    ])

# Create DataFrame
columns = [
    "attendance_percentage",
    "current_gpa",
    "study_hours_per_day",
    "gym_visits_per_week",
    "workout_duration_minutes",
    "preferred_sport",
    "sports_practice_hours_per_week",
    "coach_guided_sessions",
    "fitness_level",
    "sports_skill_level",
    "stress_level",
    "sleep_hours",
    "time_management_score",
    "overall_personality_score"
]

df = pd.DataFrame(data, columns=columns)

# Save dataset
df.to_csv("student_personality_fitness_data.csv", index=False)

print("✅ Synthetic dataset generated successfully!")
print(df.head())

pip install snowflake-connector-python pandas

pip install snowflake-connector-python pandas scikit-learn joblib

import snowflake.connector
import pandas as pd

# ------------------ Snowflake Connection ------------------
conn = snowflake.connector.connect(
    user="pratiksha11",
    password="LBh9yLWu2bCqra7",
    account="ENFFEGU-BT98807",
    warehouse="COMPUTE_WH",
    database="STUDENT_WELLBEING_DB",
    schema="WELLBEING"
)

query = """
SELECT *
FROM STUDENT_PERSONALITY_DATA
"""

df = pd.read_sql(query, conn)
conn.close()

print("✅ Data fetched from Snowflake")
print(df.head())
print("Shape:", df.shape)

"""# **EDA**"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
corr = df.corr()
sns.heatmap(corr, cmap="coolwarm", annot=False)
plt.title("Correlation Heatmap of Student Wellbeing Features")
plt.show()

fitness_bins = pd.cut(
    df["FITNESS_LEVEL"],
    bins=[0, 3, 6, 10],
    labels=["Low Fitness", "Moderate Fitness", "High Fitness"]
)

fitness_personality = (
    df.groupby(fitness_bins)["OVERALL_PERSONALITY_SCORE"]
    .mean()
)


import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
fitness_personality.plot(kind="bar")
plt.xlabel("Fitness Level Group")
plt.ylabel("Average Personality Score")
plt.title("Average Personality Score by Fitness Level")
plt.show()

gym_bins = pd.cut(
    df["GYM_VISITS_PER_WEEK"],
    bins=[-1, 1, 3, 7],
    labels=["Low", "Medium", "High"]
)

gym_personality = pd.crosstab(
    gym_bins,
    df["PERSONALITY_BINARY"],
    normalize="index"
)

gym_personality.plot(
    kind="bar",
    stacked=True,
    figsize=(6,4)
)

plt.xlabel("Gym Visit Frequency")
plt.ylabel("Proportion")
plt.title("Gym Consistency vs Personality Category")
plt.legend(["Needs Improvement", "Good"])
plt.show()

plt.figure(figsize=(6,4))
df.boxplot(
    column="TIME_MANAGEMENT_SCORE",
    by="PERSONALITY_BINARY"
)
plt.xlabel("Personality Category (0 = Needs Improvement, 1 = Good)")
plt.ylabel("Time Management Score")
plt.title("Time Management vs Personality Category")
plt.suptitle("")
plt.show()

"""# **data preprocessing**"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["PREFERRED_SPORT"] = le.fit_transform(df["PREFERRED_SPORT"])

def binary_category(score):
    if score < 6:
        return 0   # Needs Improvement
    else:
        return 1   # Good

df["PERSONALITY_BINARY"] = df["OVERALL_PERSONALITY_SCORE"].apply(binary_category)

X_reg = df.drop(
    ["OVERALL_PERSONALITY_SCORE", "PERSONALITY_BINARY"],
    axis=1
)
y_reg = df["OVERALL_PERSONALITY_SCORE"]

X_clf = df.drop(
    ["OVERALL_PERSONALITY_SCORE", "PERSONALITY_BINARY"],
    axis=1
)
y_clf = df["PERSONALITY_BINARY"]

"""# **model training**"""

from sklearn.model_selection import train_test_split

X_reg = df.drop(
    ["OVERALL_PERSONALITY_SCORE", "PERSONALITY_BINARY"],
    axis=1
)
y_reg = df["OVERALL_PERSONALITY_SCORE"]

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

lr = LinearRegression()
lr.fit(X_train_reg, y_train_reg)

y_pred_lr = lr.predict(X_test_reg)

print("Linear Regression")
print("R2:", r2_score(y_test_reg, y_pred_lr))
print("MAE:", mean_absolute_error(y_test_reg, y_pred_lr))

from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(
    n_estimators=100,
    max_depth=6,
    random_state=42
)

rf_reg.fit(X_train_reg, y_train_reg)

y_pred_rf_reg = rf_reg.predict(X_test_reg)

print("\nRandom Forest Regressor")
print("R2:", r2_score(y_test_reg, y_pred_rf_reg))
print("MAE:", mean_absolute_error(y_test_reg, y_pred_rf_reg))

X_clf = df.drop(
    ["OVERALL_PERSONALITY_SCORE", "PERSONALITY_BINARY"],
    axis=1
)
y_clf = df["PERSONALITY_BINARY"]

X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(
    X_clf, y_clf, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(
    n_estimators=100,
    max_depth=6,
    random_state=42
)

rf_clf.fit(X_train_clf, y_train_clf)

y_pred_clf = rf_clf.predict(X_test_clf)

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test_clf, y_pred_clf)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Needs Improvement", "Good"]
)

disp.plot(cmap="Blues")
plt.title("2×2 Confusion Matrix – Random Forest Classifier")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(
    y_test_clf,
    y_pred_clf,
    target_names=["Needs Improvement", "Good"]
))

"""# **dashboard**"""





!pip install gradio seaborn scikit-learn

import gradio as gr
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

# ==================================================
# LOAD DATA
# ==================================================
df = pd.read_csv("student_personality_fitness_data.csv")
df.columns = df.columns.str.strip().str.upper()

# ==================================================
# LOAD MODELS + ENCODER
# ==================================================
rf_reg = joblib.load("rf_regressor.pkl")
rf_clf = joblib.load("rf_classifier.pkl")
sport_encoder = joblib.load("sport_encoder.pkl")

# Encode sport column
df["PREFERRED_SPORT"] = sport_encoder.transform(df["PREFERRED_SPORT"])

# Binary target
df["PERSONALITY_BINARY"] = df["OVERALL_PERSONALITY_SCORE"].apply(
    lambda x: 1 if x >= 6 else 0
)

# ==================================================
# PREDICTION FUNCTION
# ==================================================
def predict_personality(attendance, gpa, study_hours, gym_visits, workout,
                        sport, sports_hours, coach, fitness, skill,
                        stress, sleep, time_mgmt):

    sport_code = sport_encoder.transform([sport])[0]

    input_df = pd.DataFrame([{
        "ATTENDANCE_PERCENTAGE": attendance,
        "CURRENT_GPA": gpa,
        "STUDY_HOURS_PER_DAY": study_hours,
        "GYM_VISITS_PER_WEEK": gym_visits,
        "WORKOUT_DURATION_MINUTES": workout,
        "PREFERRED_SPORT": sport_code,
        "SPORTS_PRACTICE_HOURS_PER_WEEK": sports_hours,
        "COACH_GUIDED_SESSIONS": coach,
        "FITNESS_LEVEL": fitness,
        "SPORTS_SKILL_LEVEL": skill,
        "STRESS_LEVEL": stress,
        "SLEEP_HOURS": sleep,
        "TIME_MANAGEMENT_SCORE": time_mgmt
    }])

    score = rf_reg.predict(input_df)[0]
    category = rf_clf.predict(input_df)[0]

    if category == 1:
        label = "🟢 Good Personality Development"
        advice = "Maintain balanced academics, fitness, and stress management."
    else:
        label = "🔴 Needs Improvement"
        advice = "Increase fitness activity, improve sleep, and manage stress."

    return round(score, 2), label, advice

# ==================================================
# EDA PLOTS
# ==================================================
def plot_correlation():
    numeric_df = df.select_dtypes(include="number")
    fig, ax = plt.subplots(figsize=(6,4))
    sns.heatmap(numeric_df.corr(), cmap="coolwarm", ax=ax)
    return fig

def plot_fitness_vs_personality():
    avg_fit = df.groupby("FITNESS_LEVEL")["OVERALL_PERSONALITY_SCORE"].mean()
    fig, ax = plt.subplots(figsize=(6,4))
    avg_fit.plot(kind="bar", ax=ax)
    ax.set_ylabel("Average Personality Score")
    return fig

# ==================================================
# CONFUSION MATRIX
# ==================================================
def plot_confusion():
    X = df.drop(["OVERALL_PERSONALITY_SCORE", "PERSONALITY_BINARY"], axis=1)
    y = df["PERSONALITY_BINARY"]
    y_pred = rf_clf.predict(X)

    cm = confusion_matrix(y, y_pred)
    fig, ax = plt.subplots()
    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=["Needs Improvement", "Good"]
    )
    disp.plot(ax=ax)
    return fig

def get_classification_report():
    X = df.drop(["OVERALL_PERSONALITY_SCORE", "PERSONALITY_BINARY"], axis=1)
    y = df["PERSONALITY_BINARY"]
    y_pred = rf_clf.predict(X)
    return classification_report(y, y_pred)

# ==================================================
# GRADIO UI
# ==================================================
with gr.Blocks(title="Student Personality Enhancement Dashboard") as app:

    gr.Markdown("""
    # 🎯 Student Personality Enhancement Program
    This system predicts **student personality development** using academic,
    fitness, and sports-related factors.
    """)

    with gr.Tab("🔮 Personality Prediction"):
        with gr.Row():
            with gr.Column():
                attendance = gr.Slider(60, 100, value=80, label="Attendance (%)")
                gpa = gr.Slider(5, 10, value=8, label="Current GPA")
                study_hours = gr.Slider(1, 8, value=4, label="Study Hours per Day")
                gym_visits = gr.Slider(0, 7, value=3, label="Gym Visits per Week")
                workout = gr.Slider(20, 120, value=60, label="Workout Duration (min)")
                sport = gr.Dropdown(
                    sport_encoder.classes_.tolist(),
                    label="Preferred Sport"
                )
                sports_hours = gr.Slider(0, 10, value=4, label="Sports Practice Hours / Week")
                coach = gr.Radio([0, 1], label="Coach Guided Sessions")
                fitness = gr.Slider(1, 10, value=6, label="Fitness Level")
                skill = gr.Slider(1, 10, value=6, label="Sports Skill Level")
                stress = gr.Slider(1, 10, value=4, label="Stress Level")
                sleep = gr.Slider(4, 9, value=7, label="Sleep Hours")
                time_mgmt = gr.Slider(1, 10, value=7, label="Time Management Score")

                btn = gr.Button("Predict Personality")

            with gr.Column():
                score_out = gr.Number(label="Predicted Personality Score")
                label_out = gr.Textbox(label="Personality Category")
                advice_out = gr.Textbox(label="Recommendation")

        btn.click(
            predict_personality,
            inputs=[attendance, gpa, study_hours, gym_visits, workout,
                    sport, sports_hours, coach, fitness, skill,
                    stress, sleep, time_mgmt],
            outputs=[score_out, label_out, advice_out]
        )

    with gr.Tab("📊 Exploratory Data Analysis"):
        gr.Markdown("### Correlation Analysis")
        gr.Plot(plot_correlation)

        gr.Markdown("### Fitness Level vs Personality Score")
        gr.Plot(plot_fitness_vs_personality)

    with gr.Tab("📉 Model Evaluation"):
        gr.Markdown("### Confusion Matrix (Random Forest Classifier)")
        gr.Plot(plot_confusion)

        gr.Markdown("### Classification Report")
        gr.Textbox(get_classification_report, lines=10)

# ==================================================
# LAUNCH APP
# ==================================================
app.launch(share=True)

